// <auto-generated> This file has been auto generated by EF Core Power Tools. </autogenerated>

using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Configuration;
using System;
using System.Collections.Generic;

namespace WasteCollection.Entities.HuyNQ.Models;

public partial class WasteCollectionDbContext : DbContext
{
    public WasteCollectionDbContext()
    {
    }

    public WasteCollectionDbContext(DbContextOptions<WasteCollectionDbContext> options)
        : base(options)
    {
    }

    public virtual DbSet<CollectorAssignmentsHuyNq> CollectorAssignmentsHuyNqs { get; set; }

    public virtual DbSet<ReportsHuyNq> ReportsHuyNqs { get; set; }

    public virtual DbSet<SystemUserAccount> SystemUserAccounts { get; set; }

    public static string GetConnectionString(string connectionStringName)
    {
        var config = new ConfigurationBuilder()
            .SetBasePath(AppDomain.CurrentDomain.BaseDirectory)
            .AddJsonFile("appsettings.json")
            .Build();

        string connectionString = config.GetConnectionString(connectionStringName);
        return connectionString;
    }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        => optionsBuilder.UseSqlServer(GetConnectionString("DefaultConnection")).UseQueryTrackingBehavior(QueryTrackingBehavior.NoTracking);

    //    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    //#warning To protect potentially sensitive information in your connection string, you should move it out of source code. You can avoid scaffolding the connection string by using the Name= syntax to read it from configuration - see https://go.microsoft.com/fwlink/?linkid=2131148. For more guidance on storing connection strings, see https://go.microsoft.com/fwlink/?LinkId=723263.
    //        => optionsBuilder.UseSqlServer("Data Source=127.0.0.1;Initial Catalog=WasteCollectionDb;Persist Security Info=True;User ID=sa;Password=Huy12345@;Encrypt=False;Trust Server Certificate=True;Command Timeout=300");

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<CollectorAssignmentsHuyNq>(entity =>
        {
            entity.HasKey(e => e.AssignmentId).HasName("PK__Collecto__32499E7783913469");

            entity.ToTable("CollectorAssignmentsHuyNQ");

            entity.Property(e => e.AssignmentId).ValueGeneratedNever();
            entity.Property(e => e.ArrivalTime).HasColumnType("datetime");
            entity.Property(e => e.AssignedDate).HasColumnType("datetime");
            entity.Property(e => e.CollectedWeight).HasColumnType("decimal(10, 2)");
            entity.Property(e => e.CompletionTime).HasColumnType("datetime");
            entity.Property(e => e.EstimatedArrivalTime).HasColumnType("datetime");
            entity.Property(e => e.Notes).HasMaxLength(500);
            entity.Property(e => e.ProofImageUrl).HasMaxLength(500);
            entity.Property(e => e.ReportHuyNqid).HasColumnName("ReportHuyNQId");
            entity.Property(e => e.Status).HasMaxLength(50);

            entity.HasOne(d => d.ReportHuyNq).WithMany(p => p.CollectorAssignmentsHuyNqs)
                .HasForeignKey(d => d.ReportHuyNqid)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_CollectorAssignmentsHuyNQ_ReportsHuyNQ");
        });

        modelBuilder.Entity<ReportsHuyNq>(entity =>
        {
            entity.HasKey(e => e.ReportId).HasName("PK__ReportsH__D5BD4805DF099BD8");

            entity.ToTable("ReportsHuyNQ");

            entity.Property(e => e.ReportId).ValueGeneratedNever();
            entity.Property(e => e.Address).HasMaxLength(500);
            entity.Property(e => e.CreatedAt).HasColumnType("datetime");
            entity.Property(e => e.LastUpdatedAt).HasColumnType("datetime");
            entity.Property(e => e.ReportDate).HasColumnType("datetime");
        });

        modelBuilder.Entity<SystemUserAccount>(entity =>
        {
            entity.HasKey(e => e.UserAccountId);

            entity.ToTable("System.UserAccount");

            entity.Property(e => e.UserAccountId).HasColumnName("UserAccountID");
            entity.Property(e => e.ApplicationCode).HasMaxLength(50);
            entity.Property(e => e.CreatedBy).HasMaxLength(50);
            entity.Property(e => e.CreatedDate).HasColumnType("datetime");
            entity.Property(e => e.Email)
                .IsRequired()
                .HasMaxLength(150);
            entity.Property(e => e.EmployeeCode)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.FullName)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.HashedPassword)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.ModifiedBy).HasMaxLength(50);
            entity.Property(e => e.ModifiedDate).HasColumnType("datetime");
            entity.Property(e => e.Phone)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.RequestCode).HasMaxLength(50);
            entity.Property(e => e.UserName)
                .IsRequired()
                .HasMaxLength(50);
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}
