// <auto-generated> This file has been auto generated by EF Core Power Tools. </autogenerated>

using System;
using System.Collections.Generic;

namespace WasteCollection.Entities.HuyNQ.Models;

public partial class CollectorAssignmentsHuyNq
{
    public Guid AssignmentId { get; set; }

    public Guid ReportHuyNqid { get; set; }

    public DateTime? AssignedDate { get; set; }

    public string Status { get; set; }

    public DateTime? ArrivalTime { get; set; }

    public DateTime? CompletionTime { get; set; }

    public decimal? CollectedWeight { get; set; }

    public string ProofImageUrl { get; set; }

    public DateTime? EstimatedArrivalTime { get; set; }

    public string Notes { get; set; }

    public virtual ReportsHuyNq ReportHuyNq { get; set; }
}
