// <auto-generated> This file has been auto generated by EF Core Power Tools. </autogenerated>

using System;
using System.Collections.Generic;

namespace WasteCollection.Entities.HuyNQ.Models;

public partial class ReportsHuyNq
{
    public Guid ReportId { get; set; }

    public DateTime? ReportDate { get; set; }

    public string Address { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? LastUpdatedAt { get; set; }

    public virtual ICollection<CollectorAssignmentsHuyNq> CollectorAssignmentsHuyNqs { get; set; } = new List<CollectorAssignmentsHuyNq>();
}
